# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Theme Settings
#
# Review documentation to determine if you should use `theme` or `remote_theme`
# https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/#installing-the-theme

# theme                  : "minimal-mistakes-jekyll"
remote_theme             : "mmistakes/minimal-mistakes@4.24.2"
minimal_mistakes_skin    : "neon" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Settings
locale                   : "en-US"
title                    : "WheelsWelded"
title_separator          : "|"
subtitle                 : Not Really # site tagline that appears below site title in masthead
name                     : "Wheels Welded"
description              : "Building an RV-10 one rivet at a time"
url                      : https://wheelswelded.com # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl                  : # the subpath of your site, e.g. "/blog"
repository               : elvinzhou/elvinzhou.github.io # GitHub username/repo-name e.g. "mmistakes/minimal-mistakes"
teaser                   : "https://www.aopa.org/-/media/Images/AOPA-Main/News-and-Media/2019/July/0709_Sweeps_RV_10.jpg" # path of fallback teaser image, e.g. "/assets/images/500x300.png"
logo                     : "/assets/img/logo.png" # path of logo image to display in the masthead, e.g. "/assets/images/88x88.png"
masthead_title           : # overrides the website title displayed in the masthead, use " " for no title
# breadcrumbs            : false # true, false (default)
words_per_minute         : 200
comments:
  provider               : staticman # false (default), "disqus", "discourse", "facebook", "staticman", "staticman_v2", "utterances", "custom"
  disqus:
    shortname            : # https://help.disqus.com/customer/portal/articles/466208-what-s-a-shortname-
  discourse:
    server               : # https://meta.discourse.org/t/embedding-discourse-comments-via-javascript/31963 , e.g.: meta.discourse.org
  facebook:
    # https://developers.facebook.com/docs/plugins/comments
    appid                :
    num_posts            : # 5 (default)
    colorscheme          : # "light" (default), "dark"
  utterances:
    theme                : # "github-light" (default), "github-dark"
    issue_term           : # "pathname" (default)
  staticman:
    branch               : "master" # "master"
    endpoint             : "https://ww-staticman.herokuapp.com/v3/entry/github/" # "https://{your Staticman v3 API}/v3/entry/github/"
reCaptcha:
  siteKey                : "6LcpvOcUAAAAAFW41uH8BGbZlosYP4MGBJLe3Xgp"
  secret                 : "plem8jhMxrQSSooyElLMYkZmaR1RYqguiPhdNPx3P+sTl009PGqGVL0yiPYFIBduHgeTqwwTU4PlEpXedkCeb0sI/luQCqOF+OIDmMF3fk3G1Jv3xhkQcZke27LNglAjjBCnxkQsN8gheJ/JHv5XfOJa+3vKHp6saVDo2aX23QlIODXDduajIe4Wre28sR/c00AsiUfkZ/uZ0+S9NKFkcG4MdEN2PG8B8+0veOkRsFySBC7U4e2DRbTCdoIBIBrmORseWJJKe4cGJ/PMnwm9LwURkkjEDJj4r5em4Sh4oub2mOmBhbtQ+ZYU93TjCyhaoIAROLSzRezp5o+Hof8SVLZfnynbLxt+yi6uGNzu2hqUJF1GWKaeUer78G8VfL4KeuyghTBs/033fEQV0W1kJqdmXbUx4722MmUwjwpNqfwj1rupgCL+MMX8UvDWKhffiNV/1UAckSMa7HGGcjIiVMywqzPt3q4hu53IaVkYVfvwW8hUzpCgqFed5ACGnG8aH7GWlOzYArm6oDQXVNhLeMzpqtAwq5rHBaD+SSHioH++0/98bwayHR6WQMq7HQRgfFzLhMZpuPcUPo4SFZfR6/hvdOaLeHA+DNngYbLq+VdFNwhvfS+AvXd+3XFnFqd/lHPBBmmfoOzNEli6nze2MjPXplwo1CeFo+WdlPhmXfY="
atom_feed:
  path                   : # blank (default) uses feed.xml
search                   : true # true, false (default)
search_full_content      : true # true, false (default)
search_provider          : google # lunr (default), algolia, google
algolia:
  application_id         : # YOUR_APPLICATION_ID
  index_name             : # YOUR_INDEX_NAME
  search_only_api_key    : # YOUR_SEARCH_ONLY_API_KEY
  powered_by             : # true (default), false
google:
  search_engine_id       : 000831228561996617644:jo8sxrji4zg # YOUR_SEARCH_ENGINE_ID
  instant_search         : # false (default), true
# SEO Related
google_site_verification : "hgWqS_fZQzT9wZcKA7SSqqcGRIwwX64rEXH53abxZL0"
bing_site_verification   :
yandex_site_verification :
naver_site_verification  :

# Social Sharing
twitter:
  username               : "@elvin_zhou"
facebook:
  username               :
  app_id                 :
  publisher              :
og_image                 : "/assets/img/logo.png" # Open Graph/Twitter default site image
# For specifying social profiles
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type                   : # Person or Organization (defaults to Person)
  name                   : # If the user or organization name differs from the site's name
  links: # An array of links to social media profiles

# Analytics
analytics:
  provider               : google # false (default), "google", "google-universal", "custom"
  google:
    tracking_id          : UA-123209023-1
    anonymize_ip         : # true, false (default)


# Site Author
author:
  name             : "Elvin Zhou"
  avatar           : "/assets/img/logo.png" # path of avatar image, e.g. "/assets/images/bio-photo.jpg"
  bio              : "Aerospace Engineer by day, RV-10 builder by night."
  location         : "California"
  email            : "elvin@wheelswelded.com"
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/elvin_zhou"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/elvinzhou"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/elvinzho"

# Site Footer
footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/elvin_zhou"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/elvinzhou"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/elvinzho"

# Reading Files
include:
  - .htaccess
  - _pages
  - .well-known
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README
  - tmp
  - /docs # ignore Minimal Mistakes /docs
  - /test # ignore Minimal Mistakes /test
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # https://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: "America/Los_Angeles" # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones


# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache


# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache



# Archives
#  Type
#  - GitHub Pages compatible archive pages built with Liquid ~> type: liquid (default)
#  - Jekyll Archives plugin archive pages ~> type: jekyll-archives
#  Path (examples)
#  - Archive page should exist at path when using Liquid method or you can
#    expect broken links (especially with breadcrumbs enabled)
#  - <base_path>/tags/my-awesome-tag/index.html ~> path: /tags/
#  - <base_path>/categories/my-awesome-category/index.html ~> path: /categories/
#  - <base_path>/my-awesome-category/index.html ~> path: /
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
# https://github.com/jekyll/jekyll-archives
# jekyll-archives:
#   enabled:
#      - categories
#      - tags
#    layouts:
#      category: archive-taxonomy
#      tag: archive-taxonomy
#    permalinks:
#      category: /categories/:name/
#      tag: /tags/:name/


# HTML Compression
# - https://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development


# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true # true
      share: true
      related: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
